name: auto-ci-frontend

on:
  push:
    branches: [ frontend ]

jobs:
  build-image:
    runs-on: main-runner
    environment: dev
    env:
      REPO: ${{ secrets.REPO }}
      TAG: frontend
    steps:
      - name: build
        run: |
          rm -rf /workspace
          git clone git@github.com:nhd1207/DL3C.git /workspace
          cd /workspace && git checkout frontend
          docker build . -t $REPO:$TAG
          docker push $REPO:$TAG