name: auto-ci-fe

on:
  push:
    branches: [ frontend ]

env:
  REPO: ${{ secrets.REPO }}
  TAG: frontend

jobs:
  build-image:
    runs-on: main-runner
    steps:
      - name: build
        run: |
          rm -rf /workspace
          git clone git@github.com:nhd1207/DL3C.git /workspace
          git checkout nhd/dev
          docker build . -t $REPO:TAG
          docker push $REPO:$TAG